key1 = "Timestamp"
key2 = "XY&^$#*@!1234%^&"

data = {
    "Source": "172.16.226.150:54595",
    "Telemetry": {
        "node_id_str": "ios",
        "subscription_id_str": "SUB",
        "encoding_path": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
        "collection_id": 19793,
        "collection_start_time": 1607459893784,
        "msg_timestamp": 1607459893784,
        "collection_end_time": 1607459893800
    },
    "Rows": [
        {
            "Timestamp": 1607459893797,
            "Keys": {
                "interface-name": "Null0"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 0,
                "broadcast-packets-sent": 0,
                "bytes-received": 0,
                "bytes-sent": 0,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 0,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313550,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 0,
                "packets-sent": 0,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 4294967295,
                "seconds-since-packet-sent": 4294967295,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "SINT0/0/0"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 0,
                "broadcast-packets-sent": 0,
                "bytes-received": 0,
                "bytes-sent": 0,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 0,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313607,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 0,
                "packets-sent": 0,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 4294967295,
                "seconds-since-packet-sent": 4294967295,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "GigabitEthernet0/0/0/0"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 682,
                "broadcast-packets-sent": 10612,
                "bytes-received": 1226645129,
                "bytes-sent": 409621228,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 1132375,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313634,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 1312503,
                "packets-sent": 311152,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 0,
                "seconds-since-packet-sent": 0,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "GigabitEthernet0/0/0/6"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 11226,
                "broadcast-packets-sent": 69,
                "bytes-received": 2016968118,
                "bytes-sent": 5796,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 1940599,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313634,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 1979064,
                "packets-sent": 138,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 0,
                "seconds-since-packet-sent": 47340,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "GigabitEthernet0/0/0/5"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 0,
                "broadcast-packets-sent": 0,
                "bytes-received": 0,
                "bytes-sent": 0,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 0,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313634,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 0,
                "packets-sent": 0,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 4294967295,
                "seconds-since-packet-sent": 4294967295,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "GigabitEthernet0/0/0/4"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 0,
                "broadcast-packets-sent": 0,
                "bytes-received": 0,
                "bytes-sent": 0,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 0,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313634,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 0,
                "packets-sent": 0,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 4294967295,
                "seconds-since-packet-sent": 4294967295,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "GigabitEthernet0/0/0/3"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 11226,
                "broadcast-packets-sent": 69,
                "bytes-received": 1638697316,
                "bytes-sent": 5796,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 1589323,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313634,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 1627679,
                "packets-sent": 138,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 0,
                "seconds-since-packet-sent": 47340,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "GigabitEthernet0/0/0/2"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 8,
                "broadcast-packets-sent": 1,
                "bytes-received": 2518125,
                "bytes-sent": 627032,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 0,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313634,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 11898,
                "packets-sent": 2699,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 689,
                "seconds-since-packet-sent": 10791,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "GigabitEthernet0/0/0/1"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 0,
                "broadcast-packets-sent": 0,
                "bytes-received": 0,
                "bytes-sent": 0,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 0,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459864,
                "last-discontinuity-time": 1607313634,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 0,
                "packets-sent": 0,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 4294967295,
                "seconds-since-packet-sent": 4294967295,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        },
        {
            "Timestamp": 1607459893798,
            "Keys": {
                "interface-name": "MgmtEth0/RP0/CPU0/0"
            },
            "Content": {
                "applique": 0,
                "availability-flag": 0,
                "broadcast-packets-received": 0,
                "broadcast-packets-sent": 0,
                "bytes-received": 0,
                "bytes-sent": 0,
                "carrier-transitions": 0,
                "crc-errors": 0,
                "framing-errors-received": 0,
                "giant-packets-received": 0,
                "input-aborts": 0,
                "input-drops": 0,
                "input-errors": 0,
                "input-ignored-packets": 0,
                "input-overruns": 0,
                "input-queue-drops": 0,
                "last-data-time": 1607459893,
                "last-discontinuity-time": 1607313535,
                "multicast-packets-received": 0,
                "multicast-packets-sent": 0,
                "output-buffer-failures": 0,
                "output-buffers-swapped-out": 0,
                "output-drops": 0,
                "output-errors": 0,
                "output-queue-drops": 0,
                "output-underruns": 0,
                "packets-received": 0,
                "packets-sent": 0,
                "parity-packets-received": 0,
                "resets": 0,
                "runt-packets-received": 0,
                "seconds-since-last-clear-counters": 0,
                "seconds-since-packet-received": 4294967295,
                "seconds-since-packet-sent": 4294967295,
                "throttled-packets-received": 0,
                "unknown-protocol-packets-received": 0
            }
        }
    ]
}